[workspace]
changelog_path = "./CHANGELOG.md"
dependencies_update = true
git_release_enable = false
git_tag_enable = false

[[package]]
name = "varnish"
git_release_enable = true
git_release_name = "v{{ version }}"
git_tag_enable = true
git_tag_name = "v{{ version }}"
